# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-11 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('lastlogin', models.DateField(default='')),
                ('dateofbirth', models.DateField(default='')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
