# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-11 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('description', models.CharField(default='', max_length=100)),
                ('category_id', models.IntegerField()),
                ('image_id', models.IntegerField()),
                ('image_link', models.CharField(default='', max_length=100)),
                ('date_add', models.DateField(default='')),
                ('supplier', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
