# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-11 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionshop', '0003_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('employee', models.CharField(default='', max_length=100)),
                ('customer', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('money_ship', models.CharField(default='', max_length=100)),
                ('VAT', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('color', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('sum_price', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'bill_detail',
            },
        ),
        migrations.CreateModel(
            name='GroupNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'group_news',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_code', models.CharField(default='', max_length=100)),
                ('trading_date', models.DateField(default='')),
                ('store_name', models.CharField(default='', max_length=100)),
                ('trading_name', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'payment_slip',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('reply', models.CharField(default='', max_length=100)),
                ('date_reply', models.DateField(default='')),
                ('comment_id', models.IntegerField()),
            ],
            options={
                'db_table': 'reply',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('money_debt', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
