# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-11 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionshop', '0004_bill_billdetail_groupnews_image_paymentslip_reply_supplier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billdetail',
            unique_together=set([('id', 'bill_id', 'product_id')]),
        ),
    ]
