# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionshop', '0005_auto_20181111_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('color_choose', models.CharField(default='', max_length=100)),
                ('size_choose', models.CharField(default='', max_length=100)),
                ('amount', models.IntegerField()),
                ('sum_price', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField()),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(default='', max_length=100)),
                ('date', models.DateField(default='')),
                ('product_id', models.IntegerField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('title', models.CharField(default='', max_length=5000)),
                ('header', models.CharField(default='', max_length=5000)),
                ('image', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=5000)),
                ('date', models.DateField(default='')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='PaymentSlipDetail',
            fields=[
                ('payment_slip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('money', models.CharField(default='', max_length=100)),
                ('note', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'payment_slip_detail',
            },
        ),
        migrations.AlterUniqueTogether(
            name='paymentslipdetail',
            unique_together=set([('payment_slip_id', 'product_id')]),
        ),
    ]
